"""Initial schema — all tables from app.models.

The models are the single source of truth for the schema; this baseline revision
materializes them verbatim (including the JSONB variants and composite indexes).
Subsequent revisions should be autogenerated diffs against the models.
A dialect-rendered SQL dump lives in docs/schema.sql for review.

Revision ID: 0001
Revises:
Create Date: 2026-07-02

"""
from alembic import op

from app.db import Base
from app import models  # noqa: F401 — register all tables on Base.metadata

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
